# deploy-appservice-template.yml
# It deploys code into app services on Azure

parameters:
- name: environment # don't pass run-time variables
- name: webAppName
- name: subscription
- name: artifactName
  default: drop



jobs:
- deployment: DeployAppService
  environment: ${{ parameters.environment }}
  strategy: 
    runOnce:
      deploy:
        steps:
      #    - task: Docker@2
      #      displayName: 'Build Docker Image'
      #      inputs:
      #        command: 'build'
      #        Dockerfile: '**/Dockerfile'
      #        tags: 'latest'
      #    - task: Docker@2
      #      displayName: 'Login to Docker Hub (Public)'
      #      inputs:
      #        command: login
      #        containerRegistry: 'docker-hub-registry-public'
      #    - task: Docker@2
      #      displayName: 'Push Docker Image to Docker Hub (Public)'
      #      inputs:
      #        containerRegistry: 'docker-hub-registry-public'
      #        repository: 'bibhupmishra/node-northwind-app'
      #        command: 'push'

          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              kubernetesServiceConnection: '113136-bpm-cowbird-aks'
              secretName: $(imagePullSecret)
              namespace: default
              dockerRegistryEndpoint: docker-azure-registry-private

          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: '113136-bpm-cowbird-aks'
              namespace: default
              manifests: |
                $(System.DefaultWorkingDirectory)/drop/www/k8-deployment-azure-113136.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                bpm2021acr.azurecr.io/node-northwind-app:latest

