# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Pipelibe only builds the node app

trigger:
- main

pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: WhiteSource@21
  inputs:
    cwd: '$(System.DefaultWorkingDirectory)'
    projectName: 'node-northwind-app'
   

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'NPM Build Copy'
    publishLocation: 'pipeline'
  displayName: 'Publish npm build for App Service Deployment'
