# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript 

# Pipelibe only build docker image and uploads to Azure Container Registry @113136 NTT Azure Accoount

trigger:
- main

#what to clean up before the job runs (outputs | resources | all)
pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest
  demand: node.js

variables:
- group: PipelineVariableGroup

stages:

- stage: Production
  displayName: 'Deploy Code to Production Kubernetes Cluster'
  pool:
    name: "MyBuildAgents"
    vmImage: ubuntu-latest
    demand: node.js
#  dependsOn: Build
  variables: 
    Environment: Production
  jobs:
  - template: azure-subpipeline-deploy-to-k8-cluster.yaml
    parameters:
      environment: ${{ variables.environment }} 
      webAppName: '$(appServicePrefix)-prod'
      subscription: $(subscription)

