# deploy-appservice-template.yml
# It deploys code into app services on Azure

parameters:
- name: environment # don't pass run-time variables
- name: containerName
- name: imageName
  default: drop


jobs:
- deployment: DeployToWebAppService
  environment: ${{ parameters.environment }}
  strategy: 
    runOnce:
      deploy:
        steps:
        - download: none
        - task: Bash@3
          displayName: 'Remove runing docker container'
          inputs:
            inputs:
              script: |
                # Modify deployment script based on the app type
                echo "Starting deployment script run"
               