# deploy-appservice-template.yml
# It deploys code into app services on Azure

parameters:
- name: environment # don't pass run-time variables
- name: webAppName
- name: subscription
- name: artifactName
  default: drop



jobs:
- deployment: DeployAppService
  environment: ${{ parameters.environment }}
  strategy: 
    runOnce:
      deploy:
        steps:
        - download: none
        - task: KubectlInstaller@0
          inputs:
            kubectlVersion: 'latest'

        - task: Kubernetes@1
          inputs:
            connectionType: 'Azure Resource Manager'
            azureSubscriptionEndpoint: 'Visual Studio Subscription - 113136'
            azureResourceGroup: 'bpm-cowbird-rg'
            kubernetesCluster: 'bpm-cowbird-aks'
            useClusterAdmin: true
            namespace: 'default'
            command: 'apply'
            useConfigurationFile: true
            configuration: '$(Pipeline.Workspace)/drop/www/azure-k8-deployment-config.yaml'
            secretType: 'dockerRegistry'
            containerRegistryType: 'Azure Container Registry'
            azureSubscriptionEndpointForSecrets: 'Visual Studio Subscription - 113136'
            azureContainerRegistry: 'bpm2021acr.azurecr.io'
            secretName: 'acr-secret-bibhu'

