# deploy-appservice-template.yml
# It deploys code into app services on Azure

parameters:
- name: environment # don't pass run-time variables
- name: webAppName
- name: subscription
- name: artifactName
  default: drop

jobs:
- deployment: DeployToWebAppService
  environment: ${{ parameters.environment }}
  strategy: 
    runOnce:
      deploy:
        steps:
        - download: none
        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: ${{ parameters.artifactName }}
            pattern: drop/northwind.zip
            targetPath: '$(System.DefaultWorkingDirectory)'
        - task: AzureRmWebAppDeployment@4
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: ${{ parameters.subscription }}
            appType: 'webAppLinux'  #its webApp for windows based apps. webAppLinux for linux based apps
            WebAppName: ${{ parameters.webAppName }}
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/northwind.zip'
