# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript 

# Pipelibe only build docker image and uploads to Azure Container Registry @113136 NTT Azure Accoount

trigger:
- main

#what to clean up before the job runs (outputs | resources | all)
pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest
  demand: node.js

variables:
- group: PipelineVariableGroup

stages:

- stage: Build
  displayName: "Compile Code"
  jobs:
  - job: Compile
    displayName: 'Compile NPM Code' 
    steps:
    - task: CopyFiles@2
      displayName: 'Copy application code to www folder'
      inputs:
        preserveTimestamp: true
        cleanTargetFolder: true  
        sourceFolder: '$(System.DefaultWorkingDirectory)'
        targetFolder: '$(build.artifactstagingdirectory)/www'
    - task: CopyFiles@2
      displayName: 'Copy terrraform files to terraform folder'
      inputs:
        SourceFolder: terraform
        TargetFolder: '$(build.artifactstagingdirectory)/terraform'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifacts & Binaries to the drop folder'
      inputs:
        targetPath: '$(build.artifactstagingdirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'


- stage: Infrastructure
  displayName: 'Setup Infrastrucure in Azure'
  pool:
    name: "MyBuildAgents"
    vmImage: ubuntu-latest
    demand: node.js
  jobs:
  - template: azure-subpipeline-setup-appservice.yaml
    parameters:
      subscription: $(subscription)
      terraformstoragerg: $(terraformStorageRG)
      terraformstorageaccount: $(terraformStorageAccount)
      terraformcontainer: $(terraformContainer)
