# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Pipelibe only build docker image and uploads to Azure Container Registry @113136 NTT Azure Accoount

trigger:
- development

pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub-registry-public'
    repository: 'node-northwind-app'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

