version: "3"
services:
    web:
        container_name: node-northwind-app
        restart: always
        build: ./
        #image: "bpm/node-northwind-app:latest"
        ports:
            - "8092:8091"
        environment:
            - MYNWAPP_ENV=production
            - MYNWAPP_PORT=8091
            - MYNWAPP_AuthTokenKey=authtoken1
            - MYNWAPP_SessionKey=sessionkey1
            - MYNWAPP_GEOCODER_API_KEY=AIzaSyAFN7pm1QA20ojk8CA2tQnXzOHB1ryRGtM
            - MYNWAPP_ERRORLOG=true
            - MYNWAPP_MONGO_URI='mongodb://mongoadmin:passw0rd!@devopsmasterlinuxvm.centralus.cloudapp.azure.com:27017/northwind?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false'
        volumes:
            - .:/app
            #  - ./error.log:/usr/src/app/error.log