apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-northwind-deployment
  labels: 
    app: node-northwind-app
#specification for deployment
spec:
  replicas: 1 #no of pod replicas needed.
  selector:
    matchLabels:
      app: node-northwind-app
  #template applies to Pod
  template: 
    metadata:
      labels:
        app: node-northwind-app
    #specification is the blueprint of a Pod
    spec:
      containers:   
      - name: node-northwind-app
        image: bibhupmishra/node-northwind-app
        env: 
        - name: MYNWAPP_MONGO_URI
          value: 'mongodb://mongoadmin:passw0rd!@devopsmasterlinuxvm.centralus.cloudapp.azure.com:9003/northwind?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false'
        ports:
        - containerPort: 8080     
