export ENVIRONMENT=production
export PORT=9001
export SSLPORT=443
export MYNWAPP_AuthTokenKey=authtoken1
export MYNWAPP_SessionKey=sessionkey1
export GEOCODER_API_KEY=AIzaSyAFN7pm1QA20ojk8CA2tQnXzOHB1ryRGtM
