# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript 

# Pipelibe only build docker image and uploads to Azure Container Registry @113136 NTT Azure Accoount

trigger:
- main

variables:
- group: PipelineVariableGroup #its a group of variables defined in the Pipeline Library in Azure DevOps. This line of code copy them over here.


#what to clean up before the job runs (outputs | resources | all)
workspace:
  clean: all  
pool:
  name: "MyBuildAgents"
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: "Compile Code"
  jobs:
  - job: Compile
    displayName: 'Compile NPM Code' 
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install NodeJS Runtime'
    #Build the NodeJS code which will be deployed to QA "Azure App Service"
    - script: |
        npm install
        npm run build
      displayName: 'npm install and build'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'drop'
        publishLocation: 'pipeline'
      displayName: 'Publish Artifacts / Binaries to drop folder'
  - job: Dockerize
    displayName: 'Build Docker Image' 
    steps:
    - task: Docker@2
      displayName: 'Push Docker Image to Azure Container Registry (Private) on 113136'
      inputs:
        containerRegistry: 'docker-azure-registry-private'
        repository: 'node-northwind-app'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'
#    - task: Docker@2
#      displayName: 'Build Docker Image'
#      inputs:
#        command: 'build'
#        Dockerfile: '**/Dockerfile'
#        tags: 'latest'
#    - task: Docker@2
#      displayName: 'Login to Docker Hub (Public)'
#      inputs:
#        command: login
#        containerRegistry: 'docker-hub-registry-public'
#    - task: Docker@2
#      displayName: 'Push Docker Image to Docker Hub (Public)'
#      inputs:
#        containerRegistry: 'docker-hub-registry-public'
#        repository: 'bibhupmishra/node-northwind-app'
#        command: 'push'


